name: 🐛 Bug Report
description: Report typos, broken links, or errors in the book
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: "Describe the issue"
      description: "Explain what’s wrong (e.g., typo, incorrect information, broken link)."
      placeholder: "Describe the bug here..."
    validations:
      required: true
  - type: input
    id: chapter
    attributes:
      label: "Which chapter/section has this issue?"
      description: "Mention the chapter or section number if applicable."
      placeholder: "e.g., Chapter 5 - Neural Networks"
  - type: textarea
    id: suggested-fix
    attributes:
      label: "Suggested Fix (Optional)"
      description: "If you have a suggestion for fixing this issue, describe it here."
      placeholder: "Suggested fix or correction..."
